/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void win_draw1(GWinApplet appc, GWinData data) { //_CODE_:window1:642598:
  appc.background(230);
} //_CODE_:window1:642598:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  if(frame != null)
    frame.setTitle("Diffusion Curve");
  Points = new GWindow(this, "UI", 0, 0, 323, 510, false, JAVA2D);
  Points.addDrawHandler(this, "win_draw1");
  label1 = new GLabel(Points.papplet, 10, 10, 308, 127);
  label1.setTextAlign(GAlign.LEFT, GAlign.TOP);
  label1.setText("Click on the black screen to create new points \n Press 'a' to add points for a new curve \n Press 'e' to stop adding points and edit the curve \n Click on the 'Set Color' button to set the color for the curve points \n Press 1 - Lagrange, 2 - Bezier, 3 - BSpline, 4 - Catmul Rom, curve to be generated \n Click 'Execute' to generate the Diffusion Curve");
  label1.setOpaque(false);
}

// Variable declarations 
// autogenerated do not edit
GWindow Points;
GLabel label1; 


